
language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest pytest-cov sphinx numpydoc codecov sphinx_rtd_theme

script:
  - pytest --cov=./

after_success:
  - codecov
