language: python

language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest sphinx numpydoc codecov codacy-coverage sphinx_rtd_theme

script:
  - pytest